sudo: false
language: node_js
node_js:
  - lts/*
cache: npm
branches:
  only:
    - hexoRaw # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexoRaw
  local-dir: public
  fqdn: www.playhi.net

